version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wishlist
      - MYSQL_USER=ms
      - MYSQL_PASSWORD=password
  web:
    image: springboot-with-docker
    container_name: springboot-with-docker
    restart: on-failure
    depends_on:
      - db
    ports:
      - 9090:9090
    environment:
      - DATABASE_HOST=password
      - DATABASE_USER=ms
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=wishlist
      - DATABASE_PORT=3306